games = [
    "Sea of Thieves",
    "Carl on Duty: Mall Cops",
    "Battlefield 1942",
    "Undertale",
    "Fallout 76",
    "Uncharted Ocean",
    "Assassin's Creed Odyssey",
    "Destiny 2",
    "The Witcher 3: Wild Hunt",
    "Red Dead Redemption 2",
    "The Elder Scrolls V: Skyrim Special Edition",
    "Borderlands 3",
    "Halo: The Master Chief Collection",
    "ELDEN RING",
    "Valheim",
    "Starbound",
    "Divinity: Original Sin 2",
    "Metro Exodus",
    "Alien: Isolation",
    "Unturned",
    "Assassin's Creed Valhalla",
    "No Man's Sky",
    "Prey",
]